### ISSUE TITLE
Recipe conflict between sunflower seeds and yellow dye

### ISSUE THREAD

**Issue by LeoBeliik** [Vazkii/crucial2#103]
Default is sunflower seeds

![2021-03-16_14 03 28](https://user-images.githubusercontent.com/11804768/111350160-959cdd80-8660-11eb-96e7-9f75d77be028.png)

**Comment by beegyfleeg** [comment]
It is likely that this is invisible during actual gameplay, due to the way the modpack resolves clashing recipes. Take for instance the Carrot Crate from Quark, which appears in the creative inventory and shares a crafting recipe with the Carrot Create from another mod. The one from the other mod takes precedence, but both crafting recipes still appear in JEI. Likely works as intended.

**Comment by LeoBeliik** [comment]
> It is likely that this is invisible during actual gameplay, due to the way the modpack resolves clashing recipes. Take for instance the Carrot Crate from Quark, which appears in the creative inventory and shares a crafting recipe with the Carrot Create from another mod. The one from the other mod takes precedence, but both crafting recipes still appear in JEI. Likely works as intended.

You telling me people won't try to make yellow dye with a sunflower...
