### ISSUE TITLE
Please Nerf Crocodiles

### ISSUE THREAD

**Issue by f-raZ0R** [Vazkii/crucial2#107]
please vazkii I spawned in a swamp and the crocs do way too much damage please nerf

**Comment by Teacyn** [comment]
To kind of coalesce some thoughts from the discord discussion:
- Crocs are able to immediately grab you when you enter melee range. Due to the lack of any extended range melees in the pack, this results in them being inherently unfair to fight in melee, like Hoglins are. HOWEVER
    - Hoglins are generally alright in spite of this, because they are a Nether mob that make loud sounds and mostly occur in at least decently open spaces. They are an easily identifiable threat in an inherently dangerous location, that can be consistently countered either with good shield usage or ranged weaponry.
- Crocs, on the other hand, are an overworld mob that spawns in two biomes with limited visibility (especially marshes) and often difficult to traverse terrain. They're also somewhat quiet and very low to the ground, making them easy to miss in some situations. They can also hide in water, for extra spooks.
- Crocs also do not have any consistent counter other than ranged weaponry, which is difficult to use in the biomes crocs are encountered in due to bad visibility. Crocs completely bypass shields and grab you, allowing them to hit you repeatedly as soon as I-frames end and prevent you from running away, which is complicated further by the difficult to navigate terrain if you do manage to actually get out of the grab. 
- Their combination of abilities and the situations you encounter them in means that even if they did substantially less damage and had less HP, they would likely still be very obnoxious to deal with and would render swamps and marshes as the most dangerous biomes by far still.

**Comment by Vazkii** [comment]
Latest version of alex's mobs nerfs them
